### ISSUE TITLE
How to close suggest list on select?

### ISSUE THREAD

**Issue by amanshu-kataria** [ubilabs/react-geosuggest#362]
### Short description

I was trying to select a suggestion, but the suggestion list doesn't close after I select a suggestion item.
I tried using below code but it didn't work.
```
onSuggestSelect(suggest) {
    console.log(suggest);
    this._geoSuggest.blur();
}
<Geosuggest ref={el => (this._geoSuggest = el)} 
          onSuggestSelect={this.onSuggestSelect}
          suggestsHiddenClassName="suggest-hidden"
          suggestItemClassName="suggest-item"/>

```

I even tried `this._geoSuggest.hideSuggests();`, but that too didn't work.

### Expected results

By selecting a suggestion item the suggestion list should close.

**Comment by ro-ka** [comment]
The list should close itself when selecting an item… Can you record a GIF how it happens? Does it happen on the Demo site, too?

**Comment by amanshu-kataria** [comment]
@ro-ka No it doesn't happen on the demo site.
Here's the gif
![suggest](https://user-images.githubusercontent.com/13014093/32159260-bc5e9efa-bd72-11e7-9732-c6d84d4467e4.gif)

**Comment by ro-ka** [comment]
Looks like some CSS is missing. Did you read this: https://github.com/ubilabs/react-geosuggest#styling ?

**Comment by amanshu-kataria** [comment]
@ro-ka thanks for the help. The problem got solved.

**Comment by ro-ka** [comment]
Perfect! Enjoy the component! 😃

**Comment by amackintosh** [comment]
Thanks for this thread's existence.

If anyone else wanders in here, **check that above URL for a quick win:**

_Note:
The geosuggest__suggests--hidden class is added to hide the suggestion list. You should copy the style below into your CSS file._

``` css
// This closes the suggestion list
.geosuggest__suggests--hidden {
  max-height: 0;
  overflow: hidden;
  border-width: 0;
}
```

**Comment by amackintosh** [comment]
Since I still ahve this open, if anyone wants some fairly wicked CSS to start with, try this:

``` css
.geosuggest {
  margin: 0;
  padding: 0;
}

.geosuggest__input {}

.geosuggest__item--active {
  background: #3f88c5;
  color: #fff;
}

.geosuggest__suggests-wrapper {
  position: absolute;
  margin-left: 0;
}

.geosuggest__suggests {
  padding: 0;
  box-sizing: border-box;
  box-shadow: 0.4rem 0.4rem 0.4rem #e5e5e5;
  background: transparent;
  border-top: 0.1rem solid #e5e5e5;
  border-bottom: 0.1rem solid #e5e5e5;
  border-left: 0.1rem solid #e5e5e5;
  border-right: 0.1rem solid #e5e5e5;
  border-radius: 0;
  outline: 0;
  background-color: #fafafa;
}

.geosuggest__item {
  list-style-type: none;
  font-size: 1.4rem;
  line-height: 1.4rem;
  padding: 0.8rem 1.6rem 0.8rem 1.6rem;
  margin-left: 0;
}

.geosuggest__suggests--hidden {
  max-height: 0;
  overflow: hidden;
  border-width: 0;
}
```

That should save you about 2 hours :)
